### PR TITLE
Added missing functionality of UIAlertController to AlertOperation.

### PR DESCRIPTION
**Pull request by blg-andreasbraun**
The AlertOperation now support 'addTextFieldWithConfigurationHandler(_:)'

### CODE REVIEW

**Comment by danthorpe** [comment]
Hi @blg-andreasbraun - looks good! 

I'll need to refresh my memory on `AlertController` - but is it possible to add some unit tests here for the new functionality?

**Comment by blg-andreasbraun** [comment]
I don't know if that would be necessary, because the API I added just calls into the UIAlertViewController API.

A coworker is using the framework in a project and missed the ability to add a UITextField to the presented UIAlertController, so I thought it would be good to enable that by just calling the appropriate API on the internal UIAlertController :)

**Comment by blg-andreasbraun** [comment]
Actually I think now that the Operation has the complete functionality of UIAlertController, the internal 'alert' property could actually be annotated as private.

**Comment by danthorpe** [comment]
Yeah, makes sense - this is going to go into `development` and v3 which is a major version change with breaking changes.

I'll wait for you to push the change.

**Comment by blg-andreasbraun** [comment]
Done.

**Comment by danthorpe** [comment]
Very nice! @blg-andreasbraun 💚😀

**Comment by felix-dumit** [comment]
Can we have the `alert` property public again? If using this in an iPad with the alert style `.Sheet` the app will crash:

>
Fatal Exception: NSGenericException Your application has presented a UIAlertController () of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem. If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.


So we need access to the `alert` property to do something like:

`alertOperation.alert.popoverPresentationController?.barButtonItem = myBarButtonItem`

**Comment by blg-andreasbraun** [comment]
Wouldn't it be easier to expose those properties on the operation itself?

so you would have something more like 

`alertOperation.barButtonItem = myBarButtonItem`

and of cause the other properties like `sourceView` and `sourceRect`.

**Comment by felix-dumit** [comment]
Those properties wouldn't always be available, as they're really properties for the `UIPopoverPresentationController`, which is only present in the `.Sheet` variation.

I feel like we'd be wrapping too deep if we do that, and also what if I want to change some other property of the popover controller? I'd be a lot of work to add all the possible properties to the alert operation. 
It would also add extra dependencies to this library in that if UIKit changes some api we'd also have to reflect it here.

**Comment by blg-andreasbraun** [comment]
OK, on that thought, yeah that could be complicated over time...
I'll post a pull request.

**Pull request merged**
