### PR TITLE
Making GroupOperation aggregateError: a public method

### PR DESCRIPTION
**Pull request by JamieWhite**
This is so we can aggregate errors from child operations

The open issue is here: https://github.com/danthorpe/Operations/issues/115

### CODE REVIEW

**Comment by danthorpe** [comment]
Hmm - I need to make some changes to my CI scripts now (they got changed for #114).

**Comment by JamieWhite** [comment]
Admittedly this failed locally but I was convinced it couldn't have failed from my change so pushed anyway to see what CI said.

**Comment by danthorpe** [comment]
You'll also need to change the property to be visible too - just make it `public private(set) var aggregateErrors`.

I don't normally use this much as I also almost inspect errors when I override `operationDidFinish` - again thanks for the spot!

**Comment by JamieWhite** [comment]
Well I've just learned something. I didn't know public private(set) was a thing.

**Comment by JamieWhite** [comment]
So the unit tests pass for me locally. What was failing beforehand was a test on GatedOperation but I cant find the test now.

**Comment by danthorpe** [comment]
Don't worry about these build failures - it's nothing to do with your changes - will have it merged in a jiffy.

**Comment by danthorpe** [comment]
Yeah, the test suite, especially on iOS has some poor/unstable tests which fail occasionally, mostly in LocationOperationTests, but sometimes GatedOperation.

**Comment by danthorpe** [comment]
Okay, I've merged #114 into `development` which is now building - when all is well, you should be able to pull dev, push up here, and the unit tests will run in CI. I suggest you just branch again from development and add your changes - quite a bit of moving around happened today.

**Comment by JamieWhite** [comment]
test__when_gate_is_open_operation_is_performed fails for me locally

**Comment by danthorpe** [comment]
Is it an async timeout?

**Comment by JamieWhite** [comment]
aaaaaand re-running it passes. I think it's a faulty test.

The problem was XCTAssertTrue(gate.finished) randomly fails

**Comment by JamieWhite** [comment]
Big code coverage drop!

**Comment by danthorpe** [comment]
Yeah, I should probably remove/rewrite them.

**Comment by danthorpe** [comment]
Don't worry about that - it's because of path changes, and i've not updated Codecov yet....

**Comment by danthorpe** [comment]
Damnit - I think that's because it's only sending the coverage of the extension tests now, as development has somehow gone down to 26%... okay, one more ticket.

**Comment by danthorpe** [comment]
Okay, this just needs development pulled into it again. Sorry. Should be okay now.

**Comment by JamieWhite** [comment]
Sorted.

**Pull request merged**
