### PR TITLE
Add UIOperation finishing to AlertOperation action callback

### PR DESCRIPTION
**Pull request by bastianschilbe**
The UIOperation inside the AlertOperation doesn't finish. This causes two bugs: 1) The group operation which contains an AlertOperation is never finished 2) The UIOperation never releases the PresentingViewController

### CODE REVIEW

**Comment by bastianschilbe** [comment]
This was reportet in issue #174

**Comment by danthorpe** [comment]
Arr! Awesome is that all that is needed? Tests are probably failing because `danthorpe:development` has updated the Gemfile / environment dependencies

**Comment by bastianschilbe** [comment]
UIOperation seems to be designed to be finished from outside. So someone should call finish on it. Hope I understand this operation right. For me it looks like this is all to fix this issue.

**Comment by danthorpe** [comment]
Oh, I see. You are certainly correct that `UIOperation` is not finishing, but I think that is how it should be fixed. Not really sure how this got past me - I'm fixing it now in #186.

**Comment by danthorpe** [comment]
Really appreciate the input on this issue, but I think the fix needed to be made in `UIOperation` which I've done in #186. Will keep this here for now, but if #174 is now fixed, I think this can be closed.

**Comment by bastianschilbe** [comment]
I also thought about fixing UIOperation the way you did but in case use don't present the view controller the completion callback is also never called (ViewControllerDisplaStyle.displayController kind of lies about it's completion parameter).

**Comment by danthorpe** [comment]
Arr, yes, you are right. Okay, I'll sort this out.

**Comment by danthorpe** [comment]
@bastianschilbe I'm going to close this now. Thanks for the input to the project!

**Pull request closed without merging**
