### PR TITLE
- Un-ticking target for watchOS CloudKit references

### PR DESCRIPTION
**Pull request by vibrazy**
- WatchOS target wasn't building due to CloudKit references.

### CODE REVIEW

**Comment by vibrazy** [comment]
@danthorpe Hi Dan, not sure why it's not passing builkite and the details is a picture of a lovely looking dog so I can't get any more information. 
The change is not something that would of broken anything I don't think. Could you have a look into it please. Cheers

**Comment by danthorpe** [comment]
Hi @vibrazy - sorry about this! I haven't checked the watchOS target for a while - will sort it out tonight.

At the moment, @buildkite does not support opening up the builds results for projects to public. And I've got a couple of slightly unstable tests - which are fixed on #278.

**Comment by danthorpe** [comment]
Merged - thanks @vibrazy 👍 😀

**Comment by vibrazy** [comment]
@danthorpe Awesome!! Thank you for the quick merge!

**Comment by danthorpe** [comment]
@vibrazy np, you might want to check out the [release notes](https://github.com/danthorpe/Operations/releases/tag/2.9.1) for v2.9.1 too.

**Pull request merged**
