### PR TITLE
Bugfix: Retaincycle in WebpageOperation 

### PR DESCRIPTION
**Pull request by blg-andreasbraun**
I notices that WebpageOperation has an retain cycle in its current implementation.

I changed it to be a GroupOperation, because it actually is even if it only has one UIOperation.
Added a WillExecuteObsersever to setup the delegate property of SFSafariViewController.

### CODE REVIEW

**Comment by danthorpe** [comment]
Hi @blg-andreasbraun thanks for this!

I think this bug has been fixed more generally as part of `ComposedOperation<T>` and so perhaps it would make sense to just subclass that?

**Comment by blg-andreasbraun** [comment]
Hi @danthorpe,

you could be right about ComposedOperation<T>, didn't think about that.
I'll have a look into that matter and post a pull request if I can implement it nicely :)
I think I can add some documentation to this class while I'm at it.

**Comment by blg-andreasbraun** [comment]
@danthorpe 

I think I have an implementation that looks good as an ComposedOperation that also passes the existing tests.

I have one suggestion though I'd like to have your opinion on because I don't know if there are guidelines present.

the first parameter "url" is in lowercase notation, hat contradicts the way Cocoa does it, that is "URL".
ls it planned at some stage to have a code review session where someone applies guidelines?

**Comment by danthorpe** [comment]
@blg-andreasbraun - that is a really really great point about the `URL` thing. I think it makes a lot of sense to have a sanity checking and cleaning ticket for the 3.0 release which is what I'm currently working towards. So, I will create a ticket for this, and it can also cover adding in any missing documentation too.

**Pull request merged**
